'use client';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Download } from 'lucide-react';

interface PDFProps {
  title: string;
  headers: string[];
  data: any[];
  filename: string;
}

export default function PDFDownload({ title, headers, data, filename }: PDFProps) {
  const downloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(16);
    doc.text(title, 14, 20);
    doc.setFontSize(10);
    doc.text(`Generated by SmartPartner - ${new Date().toLocaleDateString()}`, 14, 28);

    const tableData = data.map((item) => Object.values(item));

    (doc as any).autoTable({
      startY: 35,
      head: [headers],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] },
    });

    doc.save(`${filename}.pdf`);
  };

  return (
    <button
      onClick={downloadPDF}
      className="flex items-center space-x-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-lg text-xs font-semibold shadow transition"
    >
      <Download className="h-4 w-4" />
      <span>Download PDF</span>
    </button>
  );
}